In [2]:
import numpy as np

A = np.array(([1,2,3],[4,5,6],[7,8,9]))

In [3]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
A[:,-2:]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [6]:
B = np.zeros((4,4))
B

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
B[1:3,1:3] = 1
B

array([[0., 0., 0., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 0., 0., 0.]])

In [8]:
C = np.zeros((4,4))
C

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
C[::2,::2] = 1
C

array([[1., 0., 1., 0.],
       [0., 0., 0., 0.],
       [1., 0., 1., 0.],
       [0., 0., 0., 0.]])