In [1]:
import numpy as np

In [5]:
A = np.ones((2,3))
A

array([[1., 1., 1.],
       [1., 1., 1.]])

In [7]:
np.random.seed(0)
np.random.randn(3,4)

array([[ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ],
       [ 1.86755799, -0.97727788,  0.95008842, -0.15135721],
       [-0.10321885,  0.4105985 ,  0.14404357,  1.45427351]])

In [11]:
np.linspace(0,10,20, dtype=int)

array([ 0,  0,  1,  1,  2,  2,  3,  3,  4,  4,  5,  5,  6,  6,  7,  7,  8,
        8,  9, 10])

In [12]:
A = np.zeros((3,2))
B = np.ones((3,2))

In [15]:
C = np.hstack((A,B))
C.shape

(3, 4)

In [17]:
D = np.vstack((A,B))
D.shape

(6, 2)

In [18]:
np.concatenate((A,B),axis=1)

array([[0., 0., 1., 1.],
       [0., 0., 1., 1.],
       [0., 0., 1., 1.]])

In [20]:
D = D.reshape((3,4))
D

array([[0., 0., 0., 0.],
       [0., 0., 1., 1.],
       [1., 1., 1., 1.]])

In [21]:
A =  np.array([1., 2., 3.])
A.shape

(3,)

In [22]:
A = A.reshape((A.shape[0],1))
A.shape

(3, 1)